# Generated by Django 6.1.1 on 2026-10-02 00:33

import contenido.imagenes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Claudia Spa', max_length=80, verbose_name='nombre')),
                ('lema', models.CharField(default='Relajación y belleza', max_length=80, verbose_name='lema')),
                ('logo', models.ImageField(blank=True, upload_to='negocio/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], message='Sube la foto en formato JPG, PNG o WebP.'), contenido.imagenes.validar_tamano], verbose_name='logo')),
                ('whatsapp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^3\\d{9}$', 'Escribe los 10 dígitos del celular. Ejemplo: 300 123 4567.')], verbose_name='WhatsApp')),
                ('telefono', models.CharField(blank=True, help_text='Para el botón Llamar.', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Escribe los 10 dígitos del número (los fijos llevan el indicativo, por ejemplo 601 234 5678).')], verbose_name='teléfono')),
                ('saludo_whatsapp', models.CharField(default='Hola, vi la página de Claudia Spa y quiero pedir información.', help_text='Mensaje que ya va escrito cuando la persona toca el botón flotante de WhatsApp.', max_length=200, verbose_name='saludo del botón de WhatsApp')),
                ('direccion', models.CharField(blank=True, max_length=120, verbose_name='dirección')),
                ('barrio', models.CharField(blank=True, max_length=60, verbose_name='barrio')),
                ('ciudad', models.CharField(blank=True, max_length=60, verbose_name='ciudad')),
                ('enlace_mapa', models.URLField(blank=True, help_text='En Google Maps: Compartir → Copiar vínculo.', verbose_name='enlace de Google Maps')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('enlace_resenas', models.URLField(blank=True, verbose_name='enlace a las reseñas de Google')),
                ('titulo_nosotros', models.CharField(default='Nuestra historia', max_length=100, verbose_name='título')),
                ('texto_nosotros', models.TextField(blank=True, help_text='Tu historia y tu experiencia. Deja una línea en blanco entre párrafos.', verbose_name='texto')),
                ('foto_duena', models.ImageField(blank=True, upload_to='negocio/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], message='Sube la foto en formato JPG, PNG o WebP.'), contenido.imagenes.validar_tamano], verbose_name='tu foto')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'datos del negocio',
                'verbose_name_plural': 'datos del negocio',
                'db_table': 'negocio',
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200, verbose_name='pregunta')),
                ('respuesta', models.TextField(verbose_name='respuesta')),
                ('visible', models.BooleanField(default=True, verbose_name='visible en la página')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
                'db_table': 'pregunta_frecuente',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre')),
                ('descripcion', models.TextField(help_text='Dos o tres líneas.', max_length=400, verbose_name='para qué sirve')),
                ('foto', models.ImageField(blank=True, upload_to='tecnologia/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], message='Sube la foto en formato JPG, PNG o WebP.'), contenido.imagenes.validar_tamano], verbose_name='foto')),
                ('visible', models.BooleanField(default=True, verbose_name='visible en la página')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'tecnología',
                'db_table': 'tecnologia',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FotoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='local/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], message='Sube la foto en formato JPG, PNG o WebP.'), contenido.imagenes.validar_tamano], verbose_name='foto')),
                ('texto_alternativo', models.CharField(help_text='Una frase corta. La leen Google y las personas que usan lector de pantalla.', max_length=150, verbose_name='qué se ve en la foto')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_local', to='contenido.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'foto del spa',
                'verbose_name_plural': 'fotos del spa',
                'db_table': 'foto_local',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
            ],
            options={
                'verbose_name': 'Nosotros',
                'verbose_name_plural': 'Nosotros',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contenido.negocio',),
        ),
        migrations.CreateModel(
            name='Diapositiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Horizontal y de buena calidad (al menos 1600 píxeles de ancho).', upload_to='slider/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], message='Sube la foto en formato JPG, PNG o WebP.'), contenido.imagenes.validar_tamano], verbose_name='imagen')),
                ('titulo', models.CharField(max_length=80, verbose_name='título')),
                ('texto', models.CharField(blank=True, max_length=160, verbose_name='texto corto')),
                ('texto_boton', models.CharField(default='Ver más', max_length=30, verbose_name='texto del botón')),
                ('destino', models.CharField(choices=[('servicio', 'Un servicio'), ('faciales', 'Página de Faciales'), ('corporales', 'Página de Corporales'), ('whatsapp', 'WhatsApp'), ('contacto', 'Página de Contacto'), ('tecnologia', 'Sección de Tecnología')], default='servicio', max_length=12, verbose_name='el botón lleva a')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Opcional, para promociones con fecha.', null=True, verbose_name='mostrar desde')),
                ('fecha_fin', models.DateField(blank=True, help_text='Opcional. Ese día todavía se muestra.', null=True, verbose_name='mostrar hasta')),
                ('servicio', models.ForeignKey(blank=True, help_text='Solo si el botón lleva a un servicio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diapositivas', to='servicios.servicio', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'diapositiva',
                'verbose_name_plural': 'diapositivas',
                'db_table': 'diapositiva',
                'ordering': ['orden', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_inicio__isnull', True), ('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='diapositiva_fechas_validas', violation_error_message='La fecha final no puede ser anterior a la inicial.')],
            },
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='día')),
                ('hora_apertura', models.TimeField(verbose_name='abre a las')),
                ('hora_cierre', models.TimeField(verbose_name='cierra a las')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='contenido.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'franja de atención',
                'verbose_name_plural': 'horario de atención',
                'db_table': 'horario_atencion',
                'ordering': ['dia_semana', 'hora_apertura'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_cierre__gt', models.F('hora_apertura'))), name='horario_cierre_despues_de_apertura', violation_error_message='La hora de cierre debe ser después de la de apertura.')],
            },
        ),
    ]
