# Generated by Django 6.1.1 on 2026-10-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diapositiva',
            name='antetitulo',
            field=models.CharField(blank=True, help_text='Opcional. Ejemplo: Promoción del mes.', max_length=40, verbose_name='texto pequeño sobre el título'),
        ),
    ]
