# Generated by Django 6.1.1 on 2026-10-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_antetitulo_diapositiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='anios_experiencia',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Opcional. Se muestra destacado, por ejemplo «15+ años de experiencia».', null=True, verbose_name='años de experiencia'),
        ),
    ]
