# Generated by Django 6.1.1 on 2026-10-02 00:33

import contenido.imagenes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(help_text='Se llena sola con el nombre. Es el final de la dirección de la página del servicio; mejor no cambiarla después de publicada.', max_length=90, unique=True, verbose_name='dirección web')),
                ('categoria', models.CharField(choices=[('facial', 'Facial'), ('corporal', 'Corporal')], max_length=10, verbose_name='categoría')),
                ('es_combo', models.BooleanField(default=False, help_text='Muestra la etiqueta «Combo».', verbose_name='es un combo')),
                ('descripcion_breve', models.CharField(help_text='Una o dos líneas. Se ve en la tarjeta del servicio.', max_length=160, verbose_name='descripción breve')),
                ('descripcion', models.TextField(help_text='Qué es, para qué sirve y qué resultados esperar. Deja una línea en blanco entre párrafos.', verbose_name='descripción completa')),
                ('ideal_para', models.TextField(blank=True, help_text='Para quién es o qué mejora. Uno por línea. Ejemplo: Piel con puntos negros.', verbose_name='ideal para')),
                ('que_incluye', models.TextField(blank=True, help_text='Los pasos del servicio, uno por línea.', verbose_name='qué incluye')),
                ('recomendaciones', models.TextField(blank=True, help_text='Cada cuánto hacerlo, cuántas sesiones o con qué combinarlo.', verbose_name='recomendaciones')),
                ('cuidados_antes', models.TextField(blank=True, help_text='Uno por línea. Ejemplo: Ven sin maquillaje.', verbose_name='cuidados antes de la cita')),
                ('cuidados_despues', models.TextField(blank=True, help_text='Uno por línea. Ejemplo: Usa bloqueador solar todos los días.', verbose_name='cuidados después de la cita')),
                ('consultar_antes', models.TextField(blank=True, help_text='Casos en los que la persona debe contarte antes de pedir la cita. Uno por línea. Ejemplo: Estás en embarazo o lactancia.', verbose_name='avísanos antes si…')),
                ('duracion_min', models.PositiveSmallIntegerField(help_text='En minutos.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)], verbose_name='duración mínima')),
                ('duracion_max', models.PositiveSmallIntegerField(help_text='En minutos. Si siempre dura lo mismo, escribe el mismo número.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)], verbose_name='duración máxima')),
                ('precio', models.PositiveIntegerField(help_text='En pesos. Puedes escribirlo con o sin puntos.', verbose_name='precio')),
                ('tipo_precio', models.CharField(choices=[('fijo', 'Fijo'), ('desde', 'Desde')], default='fijo', help_text='«Desde» se muestra así: Desde $80.000.', max_length=5, verbose_name='tipo de precio')),
                ('precio_anterior', models.PositiveIntegerField(blank=True, help_text='Opcional. Se muestra tachado para que se vea el ahorro.', null=True, verbose_name='precio anterior')),
                ('sufijo_precio', models.CharField(blank=True, help_text='Opcional. Ejemplo: por sesión.', max_length=30, verbose_name='texto después del precio')),
                ('destacado', models.BooleanField(default=False, verbose_name='mostrar en Inicio')),
                ('visible', models.BooleanField(default=True, help_text='Desmárcalo para ocultar el servicio sin borrarlo.', verbose_name='visible en la página')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'servicio',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duracion_max__gte', models.F('duracion_min'))), name='servicio_duracion_valida', violation_error_message='La duración máxima no puede ser menor que la mínima.'), models.CheckConstraint(condition=models.Q(('precio_anterior__isnull', True), ('precio_anterior__gt', models.F('precio')), _connector='OR'), name='servicio_precio_anterior_mayor', violation_error_message='El precio anterior debe ser mayor que el precio actual.')],
            },
        ),
        migrations.CreateModel(
            name='FotoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='servicios/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], message='Sube la foto en formato JPG, PNG o WebP.'), contenido.imagenes.validar_tamano], verbose_name='foto')),
                ('texto_alternativo', models.CharField(help_text='Una frase corta. La leen Google y las personas que usan lector de pantalla.', max_length=150, verbose_name='qué se ve en la foto')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='servicios.servicio', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
                'db_table': 'foto_servicio',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
