# Generated by Django 6.1.1 on 2026-10-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='duracion_por_sesion',
            field=models.BooleanField(default=False, help_text='Márcalo en paquetes o planes de varias sesiones: se muestra «Aprox. 15 a 45 min por sesión».', verbose_name='la duración es por sesión'),
        ),
    ]
